# Generated by Django 4.0.4 on 2022-06-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_request_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='companies',
        ),
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.service'),
            preserve_default=False,
        ),
    ]
